# Generated by Django 4.2.4 on 2023-08-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('doc_spec', models.CharField(max_length=200)),
                ('dep_name', models.CharField(max_length=200)),
                ('doc_image', models.ImageField(upload_to='doctors')),
            ],
        ),
    ]
