# Generated by Django 4.2.4 on 2023-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='dep_shor',
        ),
        migrations.AddField(
            model_name='doctors',
            name='dep_shor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
